# backend/nixpacks.toml

[phases.setup]
nixPkgs = ["python3"]

[phases.install]
cmds = ["python -m venv /app/.venv", "pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Melewati proses build...'"]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"